### ISSUE TITLE
horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by haif-liu** [horovod/horovod#1059]
import error:
horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

**Comment by tgaddair** [comment]
Hey @haif-liu, can you try running:

```
ldd  horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so
```

And print the results here?  It's likely that something in your LD_LIBRARY_PATH is not setup properly similar to #656.

**Comment by deepbrain** [comment]
I had the same issue that was caused by python reading the libraries from the .local folder. You need to ignore the .local libraries by setting the variable "PYTHONNOUSERSITE=1 horovodrun ..."  

To eliminate such issues, the horovod needs to be compiled statically linking all of the needed libs and avoid using the LD_LIBRARY_PATH
