### ISSUE TITLE
Should we allocate different train data to different workers manually?

### ISSUE THREAD

**Issue by shunshunyin** [horovod/horovod#1100]
**Your question:**
Should we allocate different train data to different workers manually?

**Comment by alsrgv** [comment]
@shunshunyin, no, you can allocate data randomly, but you should make sure that dataset is evenly partitioned, and every worker will execute exactly the same # of batches per epoch.

**Comment by shunshunyin** [comment]
> @shunshunyin, no, you can allocate data randomly, but you should make sure that dataset is evenly partitioned, and every worker will execute exactly the same # of batches per epoch.

Did u mean that different worker will process different data just because of data partition?  And if we do not partition and shuffle data, do different worker will process the same data?

**Comment by alsrgv** [comment]
@shunshunyin, maybe I misunderstood the question.  Yes, you should have a logic that will ensure that every worker read a different set of data.  If you're using TF, one of the modern ways is to use tf.data + shard functionality.

**Comment by shunshunyin** [comment]
> @shunshunyin, maybe I misunderstood the question. Yes, you should have a logic that will ensure that every worker read a different set of data. If you're using TF, one of the modern ways is to use tf.data + shard functionality.

Thanks for your reply, I will try your idea!

**Comment by pranoothatwar** [comment]
Hello I am new to distributed computing and I have some questions regarding the data distribution.
1. How can we partition and distribute a huge dataset over workers? What are some good practices for this in the industry?
2. Can a worker randomly sample from data which is present in other worker node?

**Comment by tgaddair** [comment]
Hey @pranoothatwar,

1. We recommend storing your data in a distributed filesystem like HDFS, in a format such as Parquet, and using a framework like [Petastorm](https://github.com/uber/petastorm) to handle partitioning among the workers. This is an approach that has been used successfully at Uber ATG, as described in a recent [blog post](https://eng.uber.com/petastorm/).
2. Typically, data is not physically partitioned among the nodes. Rather, it is logically partitioned (using offsets) and then streamed into memory as needed.  If you're coming from a Hadoop/Spark background, you might expect that data locality would be important in distributed training, but because the data needs to be shuffled between each epoch, it's not actually beneficial to do that.  So yes, every node should have access to all the data.

**Comment by pranoothatwar** [comment]
Thank you very much for the suggestions.
I will go through these links and try to incorporate in my training scripts.
Thanks again :)
