### ISSUE TITLE
Why HorovodAllreduceOp is designed to be asynchronous?

### ISSUE THREAD

**Issue by qijiaxing** [horovod/horovod#1108]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13
3. Horovod version: 0.16
4. MPI version: 3.1
5. CUDA version: 10.1
6. NCCL version: 2.4.2
7. Python version: 3.6
8. OS and version: Ubuntu 16.04

**Your question:**
I notice that `HorovodAllreduceOp` is a `AsyncOpKernel`. Does this mean that it finishes as soon as `EnqueueTensorAllreduce` returns? or it waits until the actual allreduce behind the scene 
is done?

the background is that I am thinking about implement a custom op which first allreduce a tensor  then do some computation. But I am not sure if allreduce is finished after calling `EnqueueTensorAllreduce`.

Thanks!

**Comment by tgaddair** [comment]
Hey @qijiaxing, the allreduce is not necessarily finished by the time `EnqueueTensorAllreduce` happens.  In Horovod, we support something called Tensor Fusion, where multiple tensors are allreduced together at once, which requires async operations.

However, for the purpose of creating a new op, you can definitely do something with the result of the allreduce call:

```
t2 = allreduce(t)
t3 = my_custom_op(t2)
```

That's because TensorFlow constructs a graph from your operations, and in doing so will know that it needs to wait for `allreduce(t)` to complete before calling `my_custom_op(t2)`.  So for what you're trying to do it shouldn't matter that the operation is performed asynchronously.

Note that using eager execution, `allreduce(t)` will return synchronously by default.

**Comment by qijiaxing** [comment]
Thanks for your explanation. I understand better now.
