### ISSUE TITLE
how to run on multi node multi gpu ??

### ISSUE THREAD

**Issue by Chertoganov** [horovod/horovod#1205]
time mpirun -np 4 -H f1: 2, f2: 2 -x LD_LIBRARY_PATH -x PATH -x HOROVOD_MPI_THREADS_DISABLE = 1 -x NCCL_SOCKET_IFNAME = ^ virbr0, lo -mca btl openib, self-mca pml ob1 singularity of liberationbendityberentbenthenentitybeatityberentbenthenentityberentbendybeentrybeentrybeentryEnthimberedyentheatersbeatherentbendableEntherentberentEnewsheatherentbecthypethypethyntypErntyrg python /examples/keras_mnist_advanced.py

what should I write instead of f1, f2, ... etc.
ip address of the machine and its port, and then the number of processes, for example this?
192.168.17.16:11000:2

**Comment by tgaddair** [comment]
Hey @Chertoganov, you would typically provide the hostname / IP address without the port.  MPI uses SSH, which assumes port 22 (but you can configure SSH to use a different port, if that's how your cluster is configured).  

Instead of using IP addresses, it's typically more manageable to use a hosts file.  See [this](https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/) MPI tutorial for more details.
