### ISSUE TITLE
Allow forcing use of allreduce w/o MPI being present

### ISSUE THREAD

**Issue by gibiansky** [horovod/horovod#129]
In my projects I like to first create the TF graph, and then separately run training. However, if you do this, [this line](https://github.com/uber/horovod/blob/master/horovod/tensorflow/__init__.py#L174) will trip you up, because when you create the graph (without MPI), it creates the graph w/o the allreduce, so when you use it, all your ranks end up doing their own thing instead of communicating.

It would be great if there were some way to override this check, possibly by passing another argument to `DistributedOptimizer`.

**Comment by alsrgv** [comment]
It's actually a bit more complicated since we use `size()` in `allreduce()` as well (e.g., see [here](https://github.com/uber/horovod/blob/master/horovod/tensorflow/__init__.py#L75)).

One way of solving that can be to add back TensorFlow ops for `size()`, `rank()` and `local_rank()` and use those inside `allreduce()` and `DistributedOptimizer`.  Would that solve your problem?

**Comment by gibiansky** [comment]
Oooh, good point. Wow, thanks for pointing that out, that would have really tripped me up.

I'm  not sure it's necessary to have `rank` and `local_rank` but yeah, I think the best fix would be what you said. (Easier hack is to just allow overriding size, but it's more hacky)

**Comment by alsrgv** [comment]
Mostly for completeness sake. I like symmetrical APIs :-)

I should be able to do this change shortly.  Feel free to send a PR if you get to it first though.

**Comment by alsrgv** [comment]
@gibiansky, it's quite a bit delayed, but those size ops are now available in #357.  Do you want to give it a try and let us know if they work for your use case?
