### ISSUE TITLE
Let horovodrun save per-worker log file

### ISSUE THREAD

**Issue by ppwwyyxx** [horovod/horovod#1373]
**Describe the solution you'd like**
`mpirun` can save per-worker log file. This is quite useful but currently `horovodrun` prints everything to terminal.

**Describe alternatives you've considered**
`horoodrun` a bash script which redirects outputs of the actual job to a file named after the rank?

**Comment by tgaddair** [comment]
Hey @ppwwyyxx, thanks for suggesting this.  Should be a pretty straightforward change, so happy to take a look at it.

**Comment by tgaddair** [comment]
Hey @ppwwyyxx, I noticed that `mpirun`'s behavior with `--output-filename` appears to be inconsistent with its docs for the version I'm running.  For something like `--output-filename logs` I'm getting something like:

```
logs/
    1/
        rank.0/
            stdout
            stderr
        rank.1/
            stdout
            stderr
```

Since we'll be implementing this from scratch for the Gloo controller, what would be your expectations for this feature regarding:

- Directory structure and filename organization (e.g., `<base>/<rank>/<stdout>`, `<base>/<stdout>/<rank>`, `<base>.<rank>.<stdout>`, etc.)
- Merged or unmerged stdout/stderr.
- All files on worker 0 or files placed on the workers themselves.

**Comment by ppwwyyxx** [comment]
Thanks for asking! Very appreciate it.

* I don't have a strong preference as long as I can access them. Both `base/rank/{stdout,stderr}` and `base.rank.{stdout,stderr}` make sense to me, (assuming that in the later case, `base` can be a path in a different directory).

* Unmerged would be most helpful. If stdout & stderr are merged, ideally there should be a way to tell them apart. For example, I remember at some version of mpi, it prepends each line with `<stdout>`.

* Both sound reasonable to me.

**Comment by tgaddair** [comment]
Thanks for the feedback @ppwwyyxx.  Based on your suggestion, in #1379 we went with this format:

```
logs/
        rank.0/
            stdout
            stderr
        rank.1/
            stdout
            stderr
```

All the files will be on worker-0.
