### ISSUE TITLE
training samples cannot be divisible by the number of GPUs.

### ISSUE THREAD

**Issue by CXMANDTXW** [horovod/horovod#1407]
The number of my training samples cannot be divisible by the number of GPUs.
858 train samples and 183 test samples, 4 GPUS,8 Batch size
  0%|          | 0/4 [00:00<?, ?it/s][1,0]<stdout>:26
  0%|          | 0/4 [00:00<?, ?it/s][1,3]<stdout>:25
  0%|          | 0/4 [00:00<?, ?it/s][1,1]<stdout>:26
  0%|          | 0/4 [00:00<?, ?it/s][1,2]<stdout>:26

RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Is this error caused by the above cause?
How can I fix it?

**Comment by tgaddair** [comment]
Hey @CXMANDTXW, there are a few things you can do, depending on how you're currently reading the data and what framework you're using.  If this is TensorFlow and you're using their Dataset API, for example, you can call `.take()` to ensure that each worker gets the same (lowest common denominator) number of batches each epoch.

Keras models allow you to fix the number of examples per epoch using `steps_per_epoch`.  For more specific suggestions, we'd need to know a bit more about how you're currently doing data ingestion / partitioning.

**Comment by CXMANDTXW** [comment]
hey@tgaddair, my framework is pytorch1.2.
My dataset have 1041 samples,and partition it by 0.8 to get the training sets and test sets.
Batch-size is 8,gpu 4.
It means my training sets number for each gpu =1041*0.8/32=26.025.
Now I manually assign 832 training samples which can be divisible by 32.
Is this the only way can work?This means I have to manually assign the number of training samples for each data set.This is obviously not very convenient

**Comment by tgaddair** [comment]
There's a work-in-progress PR to add support for a `join` operation that will allow you to train with imbalanced batches per worker (#1058), so this will be available soon.  

In the meantime, the typical way to address this is to calculate the number of steps you wish to perform per epoch from the number of rows in your dataset, then iterate that number of times per epoch:

```
steps_per_epoch = int(train_rows / batch_size / hvd.size())
for batch_idx in range(steps_per_epoch):
    row = train_loader_iter.next()
```

Since you know that `train_rows = 1041` the rest should be pretty straightforward.

See [pytorch_imagenet_resnet50.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py) for an example of the random sampling approach.
