### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by Dreadnut93** [horovod/horovod#1430]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) tf.Keras
2. Framework version: 1.14
3. Horovod version: 0.18.0
4. MPI version:
5. CUDA version: 10.0.130
6. NCCL version:2.4.8
7. Python version:3.6
8. OS and version:
9. GCC version:
I don't know the information about the last two points. For testing, I  was using the following docker image  https://hub.docker.com/layers/horovod/horovod/0.18.0-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6/images/sha256-a9e4813b9f2a040c1e4b60c6ababb705816961303fe258c3d02a0241f75df2a3
**Checklist:**
1. Did you search issues to find if somebody asked this question before?Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?-
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?-
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?-

**Your question:**
Hello I have a simple question regarding the output I see on my screen (command line). I am running the ResNet50 Keras script which can be found in the examples folder of Horovod. The training is done on a dataset containing 20k training and 4k validation images. Both the training and validation batch-sizes are 16. For the training I am using 3 V100 GPUs.  I am getting the following output. 

```
[1,0]<stdout>:Epoch 4/90
416/416 [==============================] - 51s 121ms/step - loss: 3.7873 - acc: 0.5485 - top_k_categorical_accuracy: 1.0000 - val_loss: 3.2724 - val_acc: 0.5533 - val_top_k_categorical_accuracy: 1.0000
```

My question is the following: The output that I see comes from one (master) gpu ([1,0]), does this show the time one gpu needs to complete one epoch or the combined time? Furthermore, I have 20k training pictures and if one epoch is 51s long, would that mean that every single gpu processes 392 images per second (20k/51s) or that all three combine process 392 images per second?

Thank you in advance!

**Comment by tgaddair** [comment]
Hey @Dreadnut93, because Horovod uses synchronous distributed training, the time it takes for one GPU / worker to train one epoch will be the same time it takes for all workers to complete one epoch.

If your total training set size is 20k and it takes 51s to train with N workers (GPUs), then each worker processed `20k / N` examples within that epoch.  That's the key insight of data-parallel distributed training: that we can divide the work to do in each epoch to speed things up.  So, in your case, the total throughput among all workers was 392 images per second.

Another way to see this is to look at the output.  You can see that worker-0 processed 416 batches.  With a batch size of 16, that means it processed 6656 images in one epoch, which is 1/3 of the total 20k.

**Comment by Dreadnut93** [comment]
@tgaddair Thank you very much for the explanation. We can close the issue.
