### ISSUE TITLE
In the mpi_controller.cc 's  line 75~77, why are not the cross_comm and displacement used after referenced?   

### ISSUE THREAD

**Issue by liuyongheng123** [horovod/horovod#1438]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) 
2. Framework version:
3. Horovod version:  0.17
4. MPI version:  4.0.1
5. CUDA version: 
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:  5.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before? no
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? no
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Your question:**
Recently I read the horovod code V0.17 for understanding how horovod completes the data-trans cross nodes. I find,  in the mpi_controller.cc , cross_comm and displacement are defined , but not used behind . And the operation of allreduce  just use the mpi_comm which duplicates from world_comm . So why the cross_comm is defined , and how does it happend that ring structure gets its formation?

**Comment by tgaddair** [comment]
Hey @liuyongheng123, for MPI specifically, the ring structure is handled externally to Horovod (MPI manages it itself).  The `local_size_at_cross_rank` you're seeing in `mpi_controller.cc` is used by the HierarchicalAllgather operation in `mpi_operations.cc` [here](https://github.com/horovod/horovod/blob/master/horovod/common/ops/mpi_operations.cc#L252).

Hierarhical allgather needs the cross comm in order to gather across ranks.
