### ISSUE TITLE
Is there pre-build cpu version Docker containers ?

### ISSUE THREAD

**Issue by Jarvis-Cai** [horovod/horovod#1445]
**Your question:**
Please ask your question here.
hi~I am a graduate from chinese. And thanks for providing the cpu version of dockerfile, but as it's known for us all, we don't have a good internet for outside. So when I build the cpu-dockerfile, it always fails owing to the internet.Could you please provide the Pre-built Docker containers of CPU version?
Thanks very much.

**Comment by tgaddair** [comment]
Hey @Jarvis-Cai, we can definitely provide some pre-built CPU docker images for you.  We typically provide images with the latest versions of Horovod, TensorFlow, and PyTorch, so TF 2.0 and PyTorch 1.2.  Would those versions work for you?

**Comment by Jarvis-Cai** [comment]
ok, that's would be great.Though I use TF1.14 now, I think it's easy to change the version by myself. Thanks very much. That will help a lot. So how could you send it to me? Do you need my e-mail please?

**Comment by Jarvis-Cai** [comment]
hi~ @tgaddair I think it twice.Is there any possible that providing Tensorflow Lite version too please?
ヽ(✿ﾟ▽ﾟ)ノ

**Comment by Jarvis-Cai** [comment]
BTW, my e-mail is 1075214539@qq.com

**Comment by tgaddair** [comment]
Hey @Jarvis-Cai, I just released a new version of Horovod with pre-built CPU Docker containers.  You can find them here: https://hub.docker.com/r/horovod/horovod/

You'll want either tag `0.18.2-tf2.0.0-torch1.3.0-mxnet1.5.0-py2.7-cpu` or `0.18.2-tf2.0.0-torch1.3.0-mxnet1.5.0-py3.6-cpu` depending on which version of Python you prefer.  Hopefully you can pull the images from there.

I didn't include TensorFlow Lite since that's mostly outside the scope of Horovod (being used for serving as opposed to training), but it should be pretty straightforward to pull these images, then make a new image that adds TensorFlow Lite in a new layer.

Hope this works for you.  Let me know if you have any questions.

**Comment by Jarvis-Cai** [comment]
hi~@tgaddair ,get it. That's very kind of you. Thanks a lot.
