### ISSUE TITLE
Can not understand tensorflow2 minst example

### ISSUE THREAD

**Issue by jusonn** [horovod/horovod#1505]
I found somewhat interesting phenomenon in example.

In the example, It does not give `shard()` API so I think the script gives a whole dataset to every process so that every process run same steps.
But it does not. 

https://github.com/horovod/horovod/blob/38e91bee84efbb5b563a4928027a75dc3974633b/examples/tensorflow2_mnist.py#L36

when i tried `horovodrun -np 1 -H localhost:1 python tensorflow2_mnist.py`
It runs 10000 steps in 43sec as expected.

But when I tried with `horovodrun -np 8 -H localhost:8 python tensorflow2_mnist.py `
It runs 1240 steps in 24 secs as not expected.

Because, as metioned in https://github.com/horovod/horovod/issues/223#issuecomment-377831331 dataset API need `shard()` to distributedSamples.

Also it gives default argument in `repeat()` which means training loop will run permanently. In tensorflow 2.0 docs says 
```
repeat
View source

repeat(count=None)

Repeats this dataset count times.

NOTE: If this dataset is a function of global state (e.g. a random number generator), then different repetitions may produce different elements.

Args:
count: (Optional.) A tf.int64 scalar tf.Tensor, representing the number of times the dataset should be repeated. The default behavior (if count is None or -1) is for the dataset be repeated indefinitely.
```

**Comment by tgaddair** [comment]
Hey @jusonn, all the MNIST examples use a "random sampling" strategy for loading the data, as opposed to a "partitioning" strategy (using `shard()`).  Instead of splitting the data, every worker iterates over a random permutation of the same dataset.  Because you're doing distributed training, you can perform fewer steps per worker, which is why each worker runs 1250 steps (10000 / 8) instead of the full 10000.
