### ISSUE TITLE
Tensor fusion seems doesn't help with decreasing Allreduce operations

### ISSUE THREAD

**Issue by jli111** [horovod/horovod#1514]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow 1.10, Keras 2.2.2
2. Framework version:
3. Horovod version: 0.13.11
4. MPI version: Cray MPICH 3.0
5. CUDA version:
6. NCCL version:
7. Python version: Python 3.7
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
Please ask your question here.
I am new to Horovod and still in the learning process of this wonderful framework.
I have some questions during my experiments and get stuck for a while, thus, would like to seek any kind helps to clarify them.

I implemented Horovod into a DL application and performed experiments on a multi-node Cray XC40 machine, each node contains 64 core and 256 hardware threads. The training model is 1D convolutional model with two 1D convolutional layers interleaved with pooling layers, followed by two ﬁnal dense layers.  I scaled the training among 8 nodes with 1 rank per node and set 128 threads per node and only use for reduction. There are 1120 training samples, each rank trains its model replica with samples in the batch size of 20. 

I used the Timeline tool to record one training epoch with 7 steps and found negotiation events have significant overhead even for reshape tensors. I have some questions regarding this situation. I did a lot of research on those questions but still feel very confused:

(1). Is the tensor reduction operated in a layer-wise way?
  - Specifically, I mean does Horovod call Allreduce once per step, or does Horovod call an Allreduce after one tensor computation of one layer? Does Horovod create different communicators for each tensor? Is there any dependency (e.g., resources, data, time) between each Allreduce events? Since I am using the multithreading mode, is there only one thread per rank responsible for calling MPI_Allreduce during communication?

(1). What is the real propose of having the negotiation phase? 
  - In my understanding, it's used for fusing tiny tensors into the fusion buffer and call MPI_Allreduce to that buffer. But in the trace file, I have 10 tensors, only 2 of them are larger than 64 MB. In each step, I can see 8 tensor fusion operation occurred (8 MEMCPY_IN_FUSION_BUFFER and 8 MEMCPY_OUT_FUSION_BUFFER), however, there are still 10 Allreduce occurred. If the tensor reduction happens once per step, then I am supposed to see only 3 Allreduce in one step instead of 10. That's why I am thinking of questions above. But if the reduction happens in each layer for tensor, I am supposed to see more Allreduce occur in different timestamps. Please correct me if I am wrong.

I attached a screenshot of my trace file. Any reply would be very helpful and appreciated! Or could you please point me to any docs or source code that has information that I am inquiring about.  
<img width="721" alt="Screen Shot 2019-11-14 at 17 22 41" src="https://user-images.githubusercontent.com/29782239/68901217-7f48df80-0703-11ea-9b5a-455455fd79e7.png">

**Comment by tgaddair** [comment]
Hey @jli111, good questions!  Let me take a stab at answering them, feel free to followup as needed:

**Is the tensor reduction operated in a layer-wise way?**

From Horovod's perspective, tensors are submitted for reduction as soon as they are available.  Every `allreduce` call made is at the tensor level of granularity.  From the framework (TensorFlow, PyTorch, etc.), the `allreduce` operation is made, but this call is not blocking.  All it does initially is submit the tensor to a queue.  

A separate thread within Horovod pulls tensors off this queue on some interval (the "cycle time") and tries to fit as many as it can into the "fusion buffer" before submitting the actual Allreduce operation to MPI, NCCL, etc.  We only make a single Allreduce call to NCCL at a time because the assumption is that each of these calls is already fully utilizing your GPU and network bandwidth.

**What is the real propose of having the negotiation phase?**

Because deep learning frameworks are often multi-threaded (e.g., TensorFlow), the tensors can arrive in different orders on different ranks.  That means we can't simply submit them for Allreduce to NCCL in a first-in first-out order.  Instead, we need to determine which tensors are ready on all ranks and have a deterministic order for all the tensors.  That's the negotiation phase.

Horovod won't wait for all tensors to arrive each step or wait to fill up the fusion buffer before making the Allreduce call.  Instead, it will greedily send tensors as soon as they're ready.  If multiple tensors are ready and small enough, they'll be fused.  But if tensors arrive slower than Horovod can process them, there will be no fusion (which is likely what you're seeing).

The timeline looks reasonable to me.  The long negotiation period for the reshape tensor appears to be caused by a long Allreduce that happened at the same time.  Once the Allreduce finished, the reshape tensor was able to Allreduce immediately.

**Comment by jli111** [comment]
Hello @tgaddair, thank you so much for answering!

Well, I still have some confusion regarding your answer. 

(1). When you say 
"We only make a single Allreduce call to NCCL at a time because the assumption is that each of these calls is already fully utilizing your GPU and network bandwidth." 
Do you mean one Allreduce for one tensor at a time or one Allreduce for multiple tensors at a time? Back to my trace file, I can see some Allreduce operations for different tensors that happened roughly at the timestamp.  But, MPI_Allreduce is a blocking function, I don't understand how can they happen at the same time? 

(2). Besides, if tensors are too late to be fused, why am I observing so many MEMCPY_IN and MEMCPY_OUT events? I am guessing these events were made but they actually didn't do anything because their average wall durations were close to 0 (< 0.1 ms). If I am correct, adjusting the cycle time to a smaller interval should be helpful to "wait“ for late tensors and fuse them.

(3). As I learned, there are explicit barriers inside MPI_Allreduce. If no tensor fusion happens, can I say it's safe to skip the negotiation phase? Because MPI_Allreduce can guarantee that everyone is ready before real reduction and successfully reduced after the function. Seems like the negotiation phase is a little redundant in this scenario.

**Comment by tgaddair** [comment]
Hey @jli111, I apologize, I didn't take a close enough look at the timeline last night and apparently misread it.  Taking a second look, it does appear that tensors are getting fused together.  

When you see multiple tensors being Allreduced at the same time on the timeline, that's tensor fusion.  In your case it appears that 10 total tensors were submitted to be Allreduced in your selection.  2 of them were not fused, 8 of them were.  

Even though 8 tensors were fused into a single call to MPI_Allreduce, we record them as 8 separate events on the timeline (because the timeline is used to track per-tensor events).  In actuality, there were only 3 calls to MPI_Allreduce, as you suggested in your first post.

Even if no tensor fusion occurs, you still need the negotiation phase, because it's possible for worker 0 to submit tensor A first while worker 1 submits tensor B first.  We need to wait for there to be a common tensor ready on all workers, which requires negotiation.

Changing cycle time has an affect on how many tensors get fused, you're right.  Having a larger cycle time (i.e., delay) increases the chance that fusion will occur, but at the cost of slowing down Allreduce for some tensors that are already ready to go.  We recommend running `horovodrun --autotune` to find the best combination of cycle time + fusion buffer size for your environment and model.

**Comment by jli111** [comment]
Great! I think this really clarifies my questions now!

Thank you so much for detailed answer!
