### ISSUE TITLE
NCCL broadcast for the Horovod broadcast operation

### ISSUE THREAD

**Issue by nvcastet** [horovod/horovod#1521]
Is there a way to use NCCL Broadcast `ncclBroadcast` for the Horovod broadcast? If not, is there a reason?
I may be wrong but from the code, it seems only Gloo, MLSL, or MPI can be picked.

**Comment by tgaddair** [comment]
Hey @nvcastet, that's a good question.  I'm not aware of any technical reason it hasn't been implemented.  Because most broadcast calls tend not to fall on the performance-critical path (i.e., training loop), it hasn't been a high priority in the past.  That said, more users are exploring broadcasting model state once per epoch or more frequently, in which case that might start to change.  Are you interested in contributing this as a PR?
