### ISSUE TITLE
what does cycle mean?

### ISSUE THREAD

**Issue by Tron-x** [horovod/horovod#1552]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
what does cycle mean?
![image](https://user-images.githubusercontent.com/7659413/69936034-8c423d00-1511-11ea-92d1-f5264c2c60c3.png)

**Comment by tgaddair** [comment]
Hey @Tron-x, the "cycle" being referred to here is the frequency with which the Horovod background thread runs.  As tensors are enqueued for allreduce from the framework (TensorFlow, PyTorch, etc.), the background thread periodically pulls tensors from that queue and populates them into the fusion buffer for allreduce.  The frequency of that process is called the cycle time, and can be configured in `horovodrun` using `--cycle-time-ms` (default: 5ms).

**Comment by chandana1332** [comment]
Can you confirm if the intuition behind setting --cycle-time-ms is, if the tensors being reduced are large, then set this to a smaller value meaning horovod will reduce tensor at a more frequent cadence and if the tensors being reduced are small, then set this to a larger value meaning horovod will wait to accumulate tensors and then perform allreduce at a less frequent cadence saving on compute?

**Comment by tgaddair** [comment]
Hey @chandana1332, your intuition is correct.  Lower cycle time means lower delays between attempts to call allreduce.  Which means fewer opportunities to batch tensors together, more network calls, etc.  But it also means less waiting around if tensors are ready.

**Comment by chandana1332** [comment]
Got it! Thank you for confirming.

What's the best way to figure the breaking point on the size of the tensor which doesn't do well with higher cycle times? 

Also, within MPI, are all processes reducing the same tensors after batching tensors? Is there a possibility that a process could be reducing one less tensor in a batch due to delays in compute, etc.

**Comment by tgaddair** [comment]
Hey @chandana1332, in general the best way to set the cycle time and fusion buffer threshold is to run with `horovodrun --autotune` to explore various combinations.  In practice, there are many things that affect the performance for different settings of those parameters.

All processes will be reducing the same tensors in each fusion buffer batch, yes.  The tensors that are fused together are determined by the coordinator (rank 0).  If there are any delays due to a slow node then it will be reported as a warning to the user.
