### ISSUE TITLE
A question about NCCLHierarchicalAllreduce.

### ISSUE THREAD

**Issue by NanYan1119** [horovod/horovod#1625]
Why use mpi allreduce instead of nccl allreduce for cross node communication when implement NCCLHierrarchicalAllreduce？

**Comment by tgaddair** [comment]
Hey @NanYan1119, from the paper [Exascale Deep Learning for Climate Analytics](https://arxiv.org/pdf/1810.01993.pdf) that introduced the hierarchical allreduce approach, the idea is that because MPI often uses tree-based communication patterns at high scale (where hierarchical allreduce is most useful), whereas NCCL prefers to use a ring to take advantage of bandwidth for nodes connected by NVLink, it makes the most sense to use MPI across nodes but NCCL within node.

I'm not sure if this tradeoff is still true given recent improvements in NCCL.  I know they now support their own hierarchical communication patterns.  @romerojosh might be able to comment further.

**Comment by chandana1332** [comment]
A clarification about hierarchial allreduce:

1. Given that MPI is used to reduce gradients across nodes, is a new MPI communicator created to reduce gradients with only one GPU from each node participating in the all reduce operation?
2. And is NCCL used to broadcast parameters within each node? Is NCCL the default?

**Comment by tgaddair** [comment]
Hey @chandana1332, to answer your questions:

1. Yes, we create a separate cross communicator for this purpose [here](https://github.com/horovod/horovod/blob/master/horovod/common/mpi/mpi_context.cc#L158).
2. Yes, we use NCCL for reduce-scatter, allgather, and broadcast ops within a node.  You can see the full implementation [here](https://github.com/horovod/horovod/blob/master/horovod/common/ops/nccl_operations.cc#L212).

Let me know if there's anything else I can help clear up.

**Comment by chandana1332** [comment]
Thank you for the clarifications. 

Incase of broadcast and gather across nodes, does Horovod use a combination of MPI and NCCL just like allreduce does?
