### ISSUE TITLE
How horovod's timeline reflects all rank information？

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#1630]
Recently, I was analyzing performance based on horovod's timeline, but there is a point of confusion about horovod's timeline:
How to understand that horovod's timeline is only recorded on rank0, but contains all rank information? How does the timeline reflect the information of other ranks?

**Comment by tgaddair** [comment]
Hey @Richie-yan, the timeline does not reflect rank-specific information.  It only gives you the time it took for different operations to complete for different tensors.  Because these ops are performed synchronously among all the workers, the times would be the same for every rank, which is why they're only recorded on rank 0.

**Comment by Richie-yan** [comment]
Thanks for your answer, I will close this question.
