### ISSUE TITLE
Any performance benchmark on alternative communication libraries?

### ISSUE THREAD

**Issue by wangli1426** [horovod/horovod#1741]
I am a big fan of Horovod and our team has been using Horovod for distribute training since last year. 

Currently, there are multiple communication libraries available to Horovod, e.g., MPI, gloo. 

As an end-user, may I ask which one is recommended and is there any benchmark comparing the performance of Horovod under different communication libraries?

Thank you.

**Comment by tgaddair** [comment]
Hey @wangli1426, that's a good question.  We do have some benchmarks on Gloo vs MPI.  The quick answer is that if you are using NCCL for GPU allreduce, we see no performance difference between Gloo and MPI for the controller.  However, if you are using Gloo for the "data plane" as well (meaning no NCCL), then there is some performance degradation from using Gloo due to the lack of shared memory and network interface load balancing.

Here's a performance comparison when NCCL is used (ResNet50 synthetic data benchmark):

<img width="604" alt="Screen Shot 2020-02-27 at 8 34 33 AM" src="https://user-images.githubusercontent.com/1742912/75464900-b783cf00-593c-11ea-892b-d6e26cfed97c.png">

And here's without NCCL:

<img width="601" alt="Screen Shot 2020-02-27 at 8 36 24 AM" src="https://user-images.githubusercontent.com/1742912/75464911-be124680-593c-11ea-9b84-d970684085d7.png">

In most cases, you'll be using NCCL, so expect performance to be roughly the same.

**Comment by wangli1426** [comment]
@tgaddair Thank you so much for your reply. It's very informative and helpful!

**Comment by ChenYuHo** [comment]
> Gloo will be required for Horovod's upcoming elastic training (autoscaling, fault tolerance) mode

@tgaddair This sounds quite interesting, are there any tracking issues or public discussions somewhere for this feature?

**Comment by tgaddair** [comment]
Hey @ChenYuHo, we have an RFC [here](https://docs.google.com/document/d/15ZoHA5AeSI_boeyIBapg9WPXKrYXMRvPytPzQWTCTn4/edit?usp=sharing) you can take a look at.
