### ISSUE TITLE
PySpark - Passing ImageSchema Rdd Data to Horovod

### ISSUE THREAD

**Issue by SriramAvatar** [horovod/horovod#1773]
**Environment:**
1. Framework: PySpark with Keras
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read? Not related
3. If your question is about docker, did you read? Not Related
4. Did you check if you question is answered in the [troubleshooting guide]? yes

**Your question:**
Question : I am trying to use horovod in pyspark/databricks for Image classification and have a few questions here.
1. I read the images using spark's ImageSchema is there a rdd way to convert it into a nDArray without bringing everything to driver memory? - Is this where petastorm is to be used?
2. In the Mnist sample in databricks, the data is stored in dbfs/ml. Then the data is accessed in parts based on ranks in horovod. Is it necessary to move the image data to the dbfs/ml ?
3. Any samples that show both petastorm and horovod together would help, thanks.

**Comment by tgaddair** [comment]
Hey @SriramAvatar, to answer your questions:

1. You can accomplish this using a map function in pyspark:

```
def to_ndarry(row):
    row = row.asDict().copy()
    # Convert the column containing the image to ndarray here
    return Row(**row)
df = df.rdd.map(to_ndarray).toDF()
``` 

In pyspark, this will be represented as an Array type, I believe.  Petastorm can be used to read this Array type data as tensors when using Horovod.

2. It's important that the data is moved to disk out of the RDD.  RDDs are not currently well-suited to distributed training, in large part because of the lack of random access by individual workers.  Storing it in dbfs is one way to do that.

3. Databricks has an example [here](https://docs.azuredatabricks.net/_static/notebooks/deep-learning/petastorm.html), we have an example for Horovod [here](https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_run.py).  You can also see how we use Petastorm for our Horovod Spark Estimators [here](https://github.com/horovod/horovod/blob/master/horovod/spark/keras/remote.py#L164).

Let me know if you have any additional questions.

**Comment by SriramAvatar** [comment]
Hi @tgaddair ,
Thanks for the response. 

1. I tried your sample but couldn't make it work with the image schema.Could you please tell me what is that I am missing here?
```
from pyspark.sql.functions import *
image_df = spark.read.format("image").load("/mnt/euretco/experiment/train/*", inferschema=True)

from pyspark.sql import Row
def to_ndarray(row):
    row = row.asDict().copy()
    # Convert the column containing the image to ndarray here
    return Row(**row)
image_df_new  = image_df.rdd.map(to_ndarray).toDF()
```
The image_df_new data does not contain the converted array. 

On points 2 and 3, I see examples about writing the rdd as a parquet using petastorm and then accessing it. My understanding is that, we cannot use parquet files with horovod, as we have to split data to workers based on ranks, is this correct?

Thanks in advance.
