### ISSUE TITLE
Example to run training on multi-sockets CPU with TF2.0

### ISSUE THREAD

**Issue by Leslie-Fang** [horovod/horovod#1775]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TF2.0
2. Framework version:
3. Horovod version: 0.19.0
4. MPI version: OPENMPI 3.0.4
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
Is there an example to use horovod and run training on multi-sockets CPU with TF2.0?
I mean run each training instance on 1 socket of CPU.

**Comment by Leslie-Fang** [comment]
The function works when I try the example: https://github.com/horovod/horovod/blob/master/examples/tensorflow2_keras_mnist.py
And the running command:
horovodrun -np 2 -H localhost:2 python mnist.py

Since my CPU has 2 sockets, but I am not sure how to make each process running on the corresponding socket?

**Comment by tgaddair** [comment]
Hey @Leslie-Fang, @nvcastet recently landed #1767 that should address this.  If you build Horovod from master, you can run:

```
horovodrun -np 2 -H localhost:2 --binding-args="-bind-to socket -map-by socket" python mnist.py
```

@nvcastet please correct me if I'm mistaken on anything above.

**Comment by nvcastet** [comment]
@tgaddair @Leslie-Fang I would also add the `-rank-by core` (https://github.com/horovod/horovod/blob/master/horovod/run/mpi_run.py#L35), it should not matter with only 2 ranks but if you have 4 ranks and 4 GPUs, it will give first 2 ranks on 1st socket and last 2 ranks on 2nd socket (which is what you want with Horovod) instead of a round-robin (rank 0,2 socket 1 and rank 1,3 socket 2).
So full command:
`horovodrun -np 2 -H localhost:2 --binding-args="-bind-to socket -map-by socket -rank-by core" python mnist.py`

**Comment by nvcastet** [comment]
FYI, adding `--mpi-args="--report-bindings"` will display the binding that MPI selected for each rank.

**Comment by Leslie-Fang** [comment]
Thanks, Guys. I will try it.

**Comment by Leslie-Fang** [comment]
Thanks all for the valuable comments.
