### ISSUE TITLE
Is this a bug

### ISSUE THREAD

**Issue by chengdianxuezi** [horovod/horovod#1794]
https://github.com/horovod/horovod/blob/52cff13dc3c4be7b6d02757855172add04a9968b/horovod/common/gloo/gloo_context.cc#L148
local_rank and cross_rank ，These two variables are reversed
  local_ctx = Rendezvous(HOROVOD_GLOO_LOCAL_PREFIX + std::to_string(local_rank),
                         rendezvous_addr_env, rendezvous_port,
                         local_rank, local_size, dev, timeout);

**Comment by tgaddair** [comment]
Hey @chengdianxuezi, this code is pretty confusing, but it's actually correct.  The idea is that we use the "cross rank" to uniquely identify the host when setting up a local communicator.  The local rank is done within a host, and every host has a unique cross rank.  Same goes for setting up a cross communicator: the local rank will uniquely identify the cross communicator because every local rank will have its own.  Does that make sense?
