### ISSUE TITLE
When/Why to distribute the epochs?

### ISSUE THREAD

**Issue by SriramAvatar** [horovod/horovod#1857]
** Epochs :**
 As I understand, horovod does a training based on data parallelism, every node trains on the different set of data. When a node trains on a subset of data, I assume all the epochs should happen on the same node. 
I see in some samples that the epochs are distributed too. Why is this?

`# Horovod: adjust number of epochs based on number of GPUs.#Check
hvd_epochs = int(math.ceil(param_epochs/ hvd.size()))`

When will one distribute the epochs and not? May be I am missing some fundamental concept. Thanks for explaining.

**Comment by tgaddair** [comment]
Hey @SriramAvatar, you're probably referring to the [keras_mnist.py](https://github.com/horovod/horovod/blob/master/examples/keras_mnist.py#L25) example.  In that example, because the data is not being partitioned among the workers, decreasing the number of epochs is equivalent to decreasing the number of steps per epoch (because we're not reshuffling between epochs).

It's mostly a toy example meant to teach you the core Horovod concepts.  For a more realistic example that shows how you would actually scale the number of batches per epoch, see: [keras_mnist_advanced.py](https://github.com/horovod/horovod/blob/master/examples/keras_mnist_advanced.py#L131).

**Comment by SriramAvatar** [comment]
Ok, thanks for the clarification
