### ISSUE TITLE
speed plunges when training locally

### ISSUE THREAD

**Issue by vycezhong** [horovod/horovod#1885]
**Environment:**
1. Framework:  mxnet-cu102 
2. Framework version: 1.6.0
3. Horovod version: 0.19.1
4. MPI version: 3.1.0 
5. CUDA version: 10.2
6. NCCL version: 2.5.6
7. Python version: 3.6
8. OS and version: ubuntu18.04lts
9. GCC version: 7.5.0

HW: p3.16xlarge 

**Bug report:**

```sh
horovodrun -np 8 -H localhost:8 python ~/repos/horovod/examples/mxnet_imagenet_resnet50.py --model resnet50_v2 --mode gluon --rec-train ~/data/ILSVRC2012/train.rec --rec-train-idx ~/data/ILSVRC2012/train.idx --rec-val ~/data/ILSVRC2012/val.rec --rec-val-idx ~/data/ILSVRC2012/val.idx --use-rec --batch-size 64 --num-epochs 120 --data-nthreads 2 --warmup-epochs 5 --lr 0.05 --lr-mode step --log-interval 1
```
At first everything worked well. but later GPUs run so slow that i thought they did not run at all. I set `log-interval` to 1 and found it did run at an extremely slow speed, around 70img/s. 

![image](https://user-images.githubusercontent.com/25879526/79633480-6d7ad500-8198-11ea-941c-36d03e8a5434.png)

[full log](https://github.com/horovod/horovod/files/4496373/hvd.log) can be found here.
 
___

BTW, I did not observe this phenomenon when training distributedly with 8 x p3.16xlarge. hvd can reach the speed of ~15000img/s. that's about 68% scaling efficiency. is that reasonable?  
```sh
horovodrun -np 64 -H xxx:8 xxx:8 xxx:8 xxx:8 xxx:8 xxx:8 xxx:8 xxx:8  python ~/repos/horovod/examples/mxnet_imagenet_resnet50.py --model resnet50_v2 --mode gluon --rec-train ~/data/ILSVRC2012/train.rec --rec-train-idx ~/data/ILSVRC2012/train.idx --rec-val ~/data/ILSVRC2012/val.rec --rec-val-idx ~/data/ILSVRC2012/val.idx --use-rec --batch-size 64 --num-epochs 120 --data-nthreads 2 --warmup-epochs 5 --lr 0.05 --lr-mode step --log-interval 50
```

my installation:
```sh
HOROVOD_NCCL_INCLUDE=/usr/local/cuda-10.2/include HOROVOD_NCCL_LIB=/usr/local/cuda-10.2/lib HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL pip install --no-cache-dir horovod
```

i found similar issue #824 but in my case the data is just on each server's ssd. 
 
```sh
ubuntu@ip-xxx:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            241G     0  241G   0% /dev
tmpfs            49G  1.1M   49G   1% /run
/dev/xvda1      993G  383G  611G  39% /
tmpfs           241G  1.1G  240G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           241G     0  241G   0% /sys/fs/cgroup
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/1480
/dev/loop2       94M   94M     0 100% /snap/core/8935
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1566
/dev/loop3       92M   92M     0 100% /snap/core/8689
tmpfs            49G     0   49G   0% /run/user/1000
```

the data path is /home/ubuntu/data, which is on /dev/xvda1.

**Comment by tgaddair** [comment]
Hey @vycezhong, does this pattern happen consistently when training on a single machine, or does it happen differently each time?  If you could create a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst), that would help us to understand what's going on.  @romerojosh, any thoughts?

For the 8 machine case, 68% scaling efficiency is pretty good for 25Gbps network on the p3.16xlarge instances.  Normally I would suggest enabling fp16 compression to improve the scaling in this situation, but since you're using MXNet it doesn't look like we've implemented that feature in MXNet (@apeforest @romerojosh, can you confirm if there's a way to do fp16 allreduce without doing fp16 forward/backward).

Certainly if you were to use the more expensive p3dn.24xlarge instances with 100Gbps NIC, you should expect to see closer to 90%+ scaling efficiency.

**Comment by vycezhong** [comment]
@tgaddair it seems that this happened by accident. i cannot reproduce it now. everything's back to normal. if I encounter this situation again later, I will report in time.

Thanks for your explanation for scaling efficiency. I open a PR https://github.com/horovod/horovod/pull/1908 to add this feature.
