### ISSUE TITLE
Hard Torchvision Dependency

### ISSUE THREAD

**Issue by justusschock** [horovod/horovod#1898]
Hi, 
we're trying to build a docker image for lightning, which also installs horovod as an extra dependency.

We noted that in https://github.com/horovod/horovod/blob/master/setup.py#L1578 you have a hard torch vision dependency.

We don't want a hard dependency on torch vision, since guys doing NLP or other stuff don't need it. 

So I just wanted to ask, whether you need a hard dependency on it and why?

Best,
Justus

**Comment by Borda** [comment]
is is used only for examples, see https://github.com/horovod/horovod/search?q=torchvision&unscoped_q=torchvision so could it be moved to optional dependencies?

**Comment by tgaddair** [comment]
Hey @justusschock, @Borda is correct that it's only used in examples, so we can definitely remove it.  I can make a PR for this today.

As a workaround for now, I think you should be able to change the requirement `horovod[pytorch]` to just `horovod` in `requirements-extra.txt` for now, since `torch` is guaranteed to already be installed (from `requirements-txt`) before you install `requirements-extra.txt`.

Let me know if that works for now.  If not, we can aim for a patch release `0.19.2` early next week.
