### ISSUE TITLE
Is it guaranteed that all replicas of reducible parameters are exactly same on all workers? 

### ISSUE THREAD

**Issue by ufimtsev** [horovod/horovod#1927]
I understand that each worker has exactly same initial parameters in the beginning, since they're broadcasted from worker 0. The parameters are then updated independently on each worker. Ideally all the updates are exactly same across all the workers. However I wanted to ask if it might be possible that parameters on different workers "diverge" at some moment either due to slightly different gradients used to update parameters (for any reason) or the updates themselves could lead to slightly different results (due to different order of summation of FP numbers maybe?). This error could then propagate leading to workers operating on different parameter sets. Is it possible? Should we add code to synchronize the parameters explicitly? 
Thanks!
-Ivan

**Comment by tgaddair** [comment]
Hi @ufimtsev, you're correct, it is possible that workers can diverge due to numerical non-determinism (like the summation order issue you mentioned).  A good policy if you observe drift between workers is to periodically perform the `broadcast` parameters op (for example, at the end of each epoch).
