### ISSUE TITLE
Comparison with pytorch self distributed training

### ISSUE THREAD

**Issue by songtaoshi** [horovod/horovod#1973]
Hi, I am a little confused about the benchmark comparison with pytorch self distributed training.  
Because recently I am surveying the best practice for distributed training and I see horovod, but I do not know what the superior in effect and speed with pytorch self distributed training. And I know your horovod is very concise for using.

**Comment by tgaddair** [comment]
Hey @songtaoshi, baseline performance between Horovod and DDP (PyTorch native distributed training) are pretty comparable.

Some notable differences include:

1. Horovod uses a parallel programming style taken from MPI, DDP instead spawns processes dynamically. As a result, DDP can sometimes suffer from pickling issues when it attempts to spawn worker processes at runtime, which is not a problem for Horovod (because it doesn't need to pickle anything to run). The tradeoff is that it's more complicated to mix single-threaded stuff with parallel stuff in Horovod, but not by much (just add `if hvd.rank() == 0` for single-threaded logic).
2. Horovod can inter-operate with MPI, and leverage useful libraries like `mpi4py`, which allows you to easily aggregate custom metrics across workers.
3. Horovod has some advanced features, like Adasum for better convergence at high scale, auto-tuning to improve allreduce performance, and fp16 gradient compression.

**Comment by songtaoshi** [comment]
Thanks for your reply!

**Comment by whatdhack** [comment]
Is there a DDP control plane analog of the Horovod control plane  ?
