### ISSUE TITLE
Make horovod on ray not requiring ssh identity file or passwordless access

### ISSUE THREAD

**Issue by yangw1234** [horovod/horovod#2271]
**Is your feature request related to a problem? Please describe.**

Horovod on Ray still requires users to have ssh passwordless access (or through identity file) from the driver to each ray node.  

Not all ray clusters meet this. It would be nice to run horovod on ray without this requirement.

**Describe the solution you'd like**

Be able to run horovod on ray without ssh passwordless access or identity file.

**Describe alternatives you've considered**
Currently no alternatives I've considered.

**Additional context**
No

**Comment by yangw1234** [comment]
some discussions on the original horovod on ray pr: https://github.com/horovod/horovod/pull/2218#discussion_r487491911

**Comment by tgaddair** [comment]
Thanks for raising this issue @yangw1234.  Because the Horovod driver does not launch the remote workers when using `RayExecutor`, I agree that passwordless ssh should not be required.  However, we do still need to identify the correct NIC to use.  This can be passed in by the user, but from your comment it sounds like we may be able to obtain this using `ray.service.get_ip_address`.  As long as we can get that info back to the driver, then it should work.

cc @richardliaw

**Comment by richardliaw** [comment]
@yangw1234 can you take a look at #2275 and see if that is what you're asking for?

@tgaddair would be great to get your eyes on it too - haven't touched nics before :)

**Comment by yangw1234** [comment]
> @yangw1234 can you take a look at #2275 and see if that is what you're asking for?
> 
> @tgaddair would be great to get your eyes on it too - haven't touched nics before :)

@richardliaw that's exactly what I am asking. Very cool! Thanks!
