### ISSUE TITLE
Why my hvd.rank() and hvd.local_rank() are always 0

### ISSUE THREAD

**Issue by TheSilverLinings** [horovod/horovod#2277]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)  PyTorch
2. Framework version:  1.1.0
3. Horovod version: 0.19.5
4. MPI version: openmpi = 4.0.5
5. CUDA version: 10.1.105
6. NCCL version:  2.7.8 from my .deb (by the way how to check this version)
7. Python version: 3.7.3
8. OS and version: ubuntu 16.04
9. GCC version: 5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes, but it is not the same.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? 
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I run my program with "horovodrun -np 8 -H localhost:8  python train_ofa_net.py".
But it alway tell me out of memory, even I reduce the batch_size or just use one GPU.

And I found that I print hvd.rank() = 0 and hvd.local_rank() all are 0. (8 progress)
Somebody say it was because I do not complete install the horovod.
And I run the examples/pytorch_mnist.py, and it give me 

zlib.error: Error -3 while decompressing data: invalid literal/length code

Please help...

**Comment by tgaddair** [comment]
Hey @TheSilverLinings, let's start by trying to figure out what's going on with the rank.

First, I'd write a simple script we can use to check that things are working correctly:

```
import horovod.torch as hvd
hvd.init()
print(hvd.rank(), hvd.size())
```

I would also suggest running `horovodrun --check-build` and sharing the results here so we can be sure that everything installed correctly.

In my experience, most of the time this issue is caused by having multiple versions of MPI installed at the same time, or in some cases installing Horovod with a different version of MPI from the one used at runtime (see: https://stackoverflow.com/questions/50242283/all-processes-have-my-rank-0-how-to-fix).  Do you know if it's possible this is the case?

If you do not need to use MPI, I would suggest try running with `horovodrun --gloo` and let me know if that solves the issue.

**Comment by TheSilverLinings** [comment]
![image](https://user-images.githubusercontent.com/32483650/93282606-5b619900-f801-11ea-83e7-cd42d115cef6.png)

I have tried the suggestions.
But I don't know whether it is ture that I installed the horovod successfully.

I also tried the link and I think the result shows I do not use MPICH library.
I installed the open MPI (4.0.2, 4.0.1, 4.0.5) many time, does it affect the result?
