### ISSUE TITLE
Can not find some c++ APIs

### ISSUE THREAD

**Issue by zhao1157** [horovod/horovod#2369]
(This might be a silly question) I searched several times through the c++ code for this function `horovod_allreduce` with no avail. Can you show me where it is defined? Thanks.

https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/tensorflow/mpi_ops.py#L110

**Comment by zhao1157** [comment]
@aavbsouza Thanks for your help. I `grep -rn horovod_allreduce`ed in https://github.com/horovod/horovod/tree/master/horovod/common/ops, and could not find any function named `horovod_allreduce`. I am really confused about this. Can you show me where it is? Thanks!

**Comment by aavbsouza** [comment]
Hello. The path to the implementation is somewhat convoluted due to the support of multiple backends of communications and tensor libraries. 

But as far I understand the path is: 

1.  Framework specific allreduce operator 

  

  Here is implemented the TensorFlow allreduce operator.  

Thttps://github.com/horovod/horovod/blob/2600b6ff7636c7f2bf5a2310182909ecb334a010/horovod/tensorflow/mpi_ops.cc#L371-L410 

 This class subclass a standard tensorflow class for async operators: 

https://github.com/tensorflow/tensorflow/blob/7743e69253bfaa85a3430bf1eae9d25e51a78468/tensorflow/core/framework/op_kernel.h#L202 

 Here the operator is registered as a TF operator https://github.com/horovod/horovod/blob/2600b6ff7636c7f2bf5a2310182909ecb334a010/horovod/tensorflow/mpi_ops.cc#L427-L438 

This operator has the same signature as the function that you are looking. 

However, the important bit is here: 

https://github.com/horovod/horovod/blob/2600b6ff7636c7f2bf5a2310182909ecb334a010/horovod/tensorflow/mpi_ops.cc#L403-L408 

 2. Add tensor to a global tensor queue 

The `EnqueueTensorAllreduce` method will put the tensor on a reduction queue. This reduction queue is used by the library to coordinate the order of the reduction of tensors. This funmction will call the method `AddToTensorQueue`. This tensor queue is located on the global state of the horovod library (see [global_state.h](https://github.com/horovod/horovod/blob/2600b6ff7636c7f2bf5a2310182909ecb334a010/horovod/common/global_state.h) ). The global state is used to initialize the Horovod controller: 

  

https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/operations.cc#L628-L646 

 3. Use responselist to perform operations 

This controller is used to manage a kind of event loop, that continuously receive/send messages to specify the order and kind of operations to be performed (see the file [operations.cc](https://github.com/horovod/horovod/blob/master/horovod/common/operations.cc), These messages are only used to control the order of reduction. The tensors added to the queue are reduced accordingly to the receiving order of the message and some other criteria for instance the message size. The next point of interest is the function [ComputeResponseList](https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/controller.cc#L63). This function builds for every step of the execution a list with the orders of the tensors that are ready to be reduced. This list is used to perform the operation as shown here: 

  

https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/operations.cc#L602-L612 

 4. Perform Operation on Tensors 

The performOperation function is somewhat complex but the execution of the operation is clearly indicated here: 

https://github.com/horovod/horovod/blob/a7de4ae47e8697e1b917b79732b63c2cfb4c2507/horovod/common/operations.cc#L314-L318 

After some more code hopping is possible to find this class: 

https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/ops/collective_operations.h#L51-L62 

This class is used as parent class for many of the communications backend for instance the MPI backend is defined as: 

https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/ops/mpi_operations.h#L33-L46 

For GPU operations first is defined a [GPUAllreduce](https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/ops/gpu_operations.h#L129) class that is used to manage GPU streams. Finally, this class is used as parent class for backend specific code, like the [NCCL](https://github.com/horovod/horovod/blob/8c210564f083d040fd125afb786d5bead4985949/horovod/common/ops/nccl_operations.h#L78) one.

**Comment by zhao1157** [comment]
@aavbsouza Thank you very much for your super helpful clarification. I just could not get my head around that when calling a c++ function whose name is defined in the source code. [TF_CUSTOM_OP](https://github.com/tensorflow/custom-op) illustrated such phenomenon and I will just accept that. Again thanks a lot!
