### ISSUE TITLE
Can I run multiprocess in a single gpu?

### ISSUE THREAD

**Issue by dk-hong** [horovod/horovod#2396]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.20.3
4. MPI version:
5. CUDA version: 11.0
6. NCCL version:
7. Python version: 3.6.9
8. OS and version: ubuntu 18.04.5
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I try to run imagenet classification task with horovod.

There are plenty of capacities in GPU memories while running it, but I don't want to use larger batch_size.

Can I run 2 or more processes in a single GPU?

If it can, is there any problem or bottleneck in that case?

(I will apply apex or DALI to reduce the whole running time.)

**Comment by tgaddair** [comment]
Hey @dk-hong, typically you want to have one process per GPU, otherwise you may run into slowdowns, as you suggest.  Some frameworks like NCCL will also not work correctly with this setup.

If you're concerned about increased batch size hurting model convergence, I would check out the [AdaSum](https://github.com/horovod/horovod/blob/master/docs/adasum_user_guide.rst) optimizer.

**Comment by dk-hong** [comment]
OK, I will read and apply that. Thank you!
