### ISSUE TITLE
Why steps_per_epoch log value shows only part of all steps while training?

### ISSUE THREAD

**Issue by orwa-te** [horovod/horovod#2412]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 2.30
3. Horovod version: 0.20.3
4. MPI version: 4.0.5
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7.7
8. OS and version: Centos 7
9. GCC version: 4.8.5

**Your question:**
I am running **Horovod** on **Spark** by submitting the app with `spark-submit --master spark://master:7070 code.py --cluster_size 2 --epochs 1` with **2** worker nodes using `horovod.tensorflow.keras` where I have (for example) a dataset of 200 training examples and `batch_size = 20`.
While training, the logs in the driver console show only **5** batches instead of 10 as follows:
```
1/5 [ =====>]
2/5 [======>]
.........
```
I know that workers share the same batch they process but with different mini-batches and so there should be 10 batches instead of 5.
Is there something I don't understand?

**Comment by tgaddair** [comment]
Hey @orwa-te, in your example, each worker is going to process half of the 200 examples, so 100 each.  Each worker will still have a batch size of 20, so that means each epoch the workers will process 5 batches each.

I think the misunderstanding here is that when you use Horovod, the effective batch size becomes 40, not 20.  If the total batch size remained the same, then Horovod would not be able to provide any speedup in training time.

**Comment by orwa-te** [comment]
I understand from your reply that even if the `batch_size` provided to `model.fit()` equals 20, then the real batch size used is the total batch_size (computed by Horovod) which is 20*2=40, right?

**Comment by tgaddair** [comment]
Yes, that's correct.

**Comment by orwa-te** [comment]
Thanks alot @tgaddair
