### ISSUE TITLE
Use TensorFlow provided version of Eigen / Flatbuffers when available

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2429]
From #2355:

> IMO this just hints at a much larger problem: You are mixing 2 different versions of Eigen: The one TF installed and which gets included via -I<prefix>/lib/python3.7/site-packages/tensorflow/include and the one you vendored as a submodule and include too.
> 
> Now depending on the file included you get either of (or even mix) those which can lead to ODR violations. Now updating the Eigen submodule to the same version TF uses resolves the problem but only for that combinations of versions. But it makes it unable to use the next Horovod with the currently released TF or any prior version. Even worse: It may work. And fail at some point under almost impossible to track conditions.
> 
> Similar reasoning applies to flatbuffers: TF uses flatbuffers itself any may use another version than Horovod includes again causing ODR violations. However this will only manifest at runtime as TF doesn't seem to install the flatbuffer headers.
> 
> I'd strongly suggest to search for a TF or system installed version of the vendored libraries before using them. find_path in combination with NO_DEFAULT_PATH can be used for that.

**Comment by Flamefire** [comment]
FTR: A usable approach to that would look like this:

```
# Load TF/MxNet/... folders, set e.g. set(Tensorflow_INCLUDE_DIRS "${Tensorflow_INCLUDE_DIRS}" PARENT_SCOPE)
find_path(Eigen3_INCLUDE_PATH Eigen/src/Core/EigenBase.h PATHS ${Tensorflow_INCLUDE_DIRS} ENV Eigen3_INCLUDE_PATH NO_DEFAULT_PATH)
find_path(Eigen3_INCLUDE_PATH Eigen/src/Core/EigenBase.h PATHS ${PROJECT_SOURCE_DIR}/third_party/eigen)
# Use ${Eigen3_INCLUDE_PATH}
```

What it does:
- PARENT_SCOPE propagates the variable value to the outer-CMakeLists where it should be used
- The first find_path searches the TF folder (if set, else ignored because no quotes(!)) and afterwards an ENV variable in case the user want's to overwrite it.
- The 2nd find_path only runs when nothing was found, searches system folders and lastly the vendored eigen
- Result: Prefers TF Eigen, allows user overwrite (if TF doesn't provide it, might reverse the order if wanted), then tries system in case TF was build with the system and only then uses the vendored eigen.

The "system" usage is especially important for flatbuffers, less so for eigen (Eigen has no good tagged releases): On our HPC system we have modules for libraries and such. Those can be found by cmake and might be used by dependencies (e.g. TF) already.
