### ISSUE TITLE
horovod cluster master without GPU

### ISSUE THREAD

**Issue by egorgam** [horovod/horovod#2461]
Hello! Can I run horovodrun in slow virtual machine (without GPU), with powerful workers (with GPU) connected by SSH? Now when I try it from that master node (ubuntu20, horovodrun0.20.3), I see exception "RuntimeError: Failed to determine if Gloo support has been built".

**Comment by tgaddair** [comment]
Hey @egorgam, yes this is certainly doable.  The error you're seeing is probably due to taking a Horovod binary compiled for the workers and running it on the driver.  If you install Horovod separately on the driver `pip install --no-cache-dir horovod`, then it should work.

If you still run into issues, feel free to share the log output when running with `horovodrun --verbose`.

**Comment by egorgam** [comment]
@tgaddair thanks for response! How I see with verbose mode, my problem is because I use reverse SSH connection (ssh -R from worker, and localhost with non-standard port in master) for remote hosts, so my shell command on master is `horovodrun --verbose -np 4 -p 43023 -H 127.0.0.1:1 python benchmark.py`. horovod is understanding localhost only as current host, and not trying to connect to remote host (by local proxy)
