### ISSUE TITLE
Race condition in CMake

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2543]
It's been reported that Horovod can fail to build non-deterministically due to what appears to be a race condition during the CMake build process.

See https://github.com/horovod/horovod/issues/2358#issuecomment-749051099.

Temporary workaround is to set `MAKEFLAGS="-j1"`.

cc @nvcastet @leezu @romerojosh

**Comment by tgaddair** [comment]
cc @flamefire in case you can share more details.

**Comment by Flamefire** [comment]
Reported that upstream: https://gitlab.kitware.com/cmake/cmake/-/issues/21623
First reaction was that FindCUDA is deprecated (replaced by first-class language support in CMake 3.8, seemingly deprecated since 3.10): https://github.com/Kitware/CMake/blob/0eead931a370eb136dd2723192528ddce7ca69d1/Modules/FindCUDA.cmake#L5

It seems to be caused by having 2 cuda_libraries with the same source file (the C++11 and compat one), removing one seemingly resolves the issue too.

I see 2 solutions:

- Use CMake 3.8+ and don't use FindCUDA anymore
- use `configure_file(... COPY_ONLY)` to copy the source file to a different location and name and add the 2nd library with that, which might solve this

As installing CMake is trivial (i.e. `pip install cmake`, or download and compile it from source, done in 5min) I'd suggest to transition to modern CMake, i.e. including solution 1

**Comment by leezu** [comment]
I think it's reasonable to transition to modern cmake. Besides the first-class cuda support, there is FindCUDAToolkits.cmake which was introduced in a more recent cmake version and is required to find the cuda toolkit libraries. As it is self-contained, we may include it in the horovod source distribution in a similar fashion as https://github.com/apache/incubator-mxnet/blob/master/cmake/upstream/FindCUDAToolkit.cmake instead of requiring a very recent cmake version
