### ISSUE TITLE
gpu memory issues when training with tf2.4 and xla

### ISSUE THREAD

**Issue by hetaoaoao** [horovod/horovod#2548]
![horovod_xla_issue](https://user-images.githubusercontent.com/16871995/102983540-32ab1700-4547-11eb-93f0-323e460551b9.jpg)
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4
3. Horovod version: 0.21.0
4. MPI version: 4.0
5. CUDA version: 11.0
6. NCCL version:  2.8.3
7. Python version: 3.8
8. OS and version: ubuntu20.04
9. GCC version:  7.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide]  (https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

The issue is, tensorflow2.4+xla combination is taking gpu memory on EVERY gpu card which ruins multigpu training, ends with oom always.
Reproduce steps are quite easy, just run https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py
with xla enabled.
After some digging, I believe it should be related to tf2.4 since everything is ok on tf2.3 with other configurations stay the same.
Any suggestions?

**Comment by tgaddair** [comment]
@DEKHTIARJonathan, have you run into this issue with XLA as well?  Seems TF is not honoring its GPU visibility rules.

**Comment by DEKHTIARJonathan** [comment]
I'm pretty sure that if you only want memory on GPU0, you need to use `CUDA_VISIBLE_DEVICES="0" horovodrun ...`

**Comment by tgaddair** [comment]
I think the problem is that we need to have visibility into multiple GPUs for Horovod to work, but TensorFlow should not be allocating memory on every GPU when we set `tf.config.visible_devices`.  Seems this isn't working correctly with XLA in the latest version.

**Comment by DEKHTIARJonathan** [comment]
We had this exact issue a 1.5 years ago. With XLA allocating memory on every GPUs.
Please open an issue on Tensorflow side, tag myself, @nluehr @bas-aarts (for NV side) and @reedwm @sanjoy (for Google side).

Please attach information to reproduce the bug.

**Comment by tgaddair** [comment]
Thanks @DEKHTIARJonathan.  @hetaoaoao can you open the issue on the TensorFlow side?

**Comment by hetaoaoao** [comment]
Ah, we've got a workaround for this.
Do 
os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=2 --tf_xla_enable_xla_devices=true"
instead of
os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=2"
resolves this issues.

**Comment by cheshire** [comment]
In general, XLA+horovod will not be as beneficial as it could be, due to missing tf2xla horovod kernels (PRs welcome!)

@hetaoaoao 
> `--tf_xla_enable_xla_devices=true`

This enables deprecated XLA:GPU devices and generally should not be done, is it possible to provide a clean reproducer for this issue? Generally we advice using `jit_compile=True` instead of autoclustering (as it's not clear what autoclustering will cluster), but it could be a bit difficult for horovod due to missing tf2xla kernels.

**Comment by romerojosh** [comment]
Wanted to briefly comment on:
>I think the problem is that we need to have visibility into multiple GPUs for Horovod to work, but TensorFlow should not be allocating memory on every GPU when we set tf.config.visible_devices. Seems this isn't working correctly with XLA in the latest version.

It isn't required for Horovod to have visibility to multiple GPUs to work, at least, not anymore. Older versions of NCCL (pre 2.4.6), did have this limitation where all GPUs on the node needed to be visible, but that is no longer the case. So a workaround to avoid TF creating a context on each GPU would be to set `CUDA_VISIBLE_DEVICES` to the local rank so that each process only sees a single GPU. This also requires making script changes to account for this (i.e. replace any device indexing by `hvd.local_rank()` with a `0` since all processes will just have a single GPU 0 visible). 

An example of doing this with OpenMPI would look something like:
```
mpirun -np 4 bash -c 'CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK python train.py'
```

**Comment by bas-aarts** [comment]
looking into this
