### ISSUE TITLE
Horovod build tied to framework versions? 

### ISSUE THREAD

**Issue by samj1912** [horovod/horovod#2566]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow/Pytorch 
2. Framework version: 1.3/1.6 (Pytorch), 2.1/2.2/2.3(TensorFlow) 
3. Horovod version:  0.21
4. MPI version: 4.0.4
5. CUDA version: 10.1 (TensorFlow) 10.2 Pytorch
6. NCCL version: 2.7.8
7. Python version: 3.7
8. OS and version: Linux, RHEL 7
9. GCC version: 4.8

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Is the horovod version tied to the framework versions? If I install horovod first with pytorch 1.3 and then update to pytorch 1.6,would it work? Similarly if I install Horovod with tensorflow 2.1 and then upgrade it to 2.3 later on would it work (as long as the cuda and nccl versions remain the same?)

**Comment by chongxiaoc** [comment]
It has been resolved recently from https://github.com/horovod/horovod/pull/2529

Horovod would throw out a warning if it finds that framework version changed from installation time.

This issue is similar to your question https://github.com/horovod/horovod/issues/2518.

The problem of using different versions of frameworks in installation time and execution time, is that, system may rise undefined-symbol errors, because the installed hovorod libraries cannot recognize new symbols from different version of frameworks, for example, `pytorch 1.6` may use some symbols which are not supported in `pytorch 1.3`.

**Comment by samj1912** [comment]
Thanks! From what I tried it looks like patch versions are fine. Minor versions are incompatible.
