### ISSUE TITLE
Does horovod on spark support fault tolerance?

### ISSUE THREAD

**Issue by maqy1995** [horovod/horovod#2682]
**Your question:**
In other words, when some tasks or hosts fail, will they be automatically restored?

**Comment by tgaddair** [comment]
Hey @maqy1995, Horovod on Spark supports fault tolerance when using the [Elastic Horovod](https://github.com/horovod/horovod/blob/master/docs/elastic.rst) API.

@EnricoMi is putting together an example [here](https://github.com/horovod/horovod/pull/2673) for reference.

**Comment by EnricoMi** [comment]
Basically, instead of calling into `horovod.spark.run`, call into `horovod.spark.run_elastic`. Moving from classic Horovod to Elastic Horovod requires the following modifications to your training script: https://horovod.readthedocs.io/en/stable/elastic_include.html#modifying-the-training-script-with-state-synchronization.

**Comment by maqy1995** [comment]
Thanks for your reply. According to these documents, it seems only support GLOO now?
if true, will tensor transfer between GPUs still use NCCL?

**Comment by EnricoMi** [comment]
Yes, Elastic Horovod on Spark only works with Gloo.

You can [enforce GPU operations to use NCCL](https://horovod.readthedocs.io/en/stable/install_include.html#environment-variables) by installing Horovod with `HOROVOD_GPU_OPERATIONS=NCCL`. Looks like NCCL is used when MPI is **not** available as the default as that environment variable only takes `MPI` or `NCCL`.

**Comment by maqy1995** [comment]
Thanks again for your reply.
