### ISSUE TITLE
Spark Estimator Memory Limit: 4 GB per node and 1 GB per worker

### ISSUE THREAD

**Issue by chongxiaoc** [horovod/horovod#2736]
**Your question:**
What is the reason for setting the limit of memory as 4GB per node and 1 GB per worker, in Spark estimator?

For example, the torch estimator is honoring this limit to set shuffling queue capacity using petastorm:
https://github.com/horovod/horovod/blob/0acb1a53cc832c8c580e03c1a29c0e14d95234a1/horovod/spark/torch/remote.py#L424

The upper bound seems very small to me, in case user can allocate up to 100GB memory per node.
I would like to understand the design philosophy of setting these limits.

@tgaddair

**Comment by tgaddair** [comment]
Hey @chongxiaoc, good question. I remember that we wanted to make sure that we put a cap on the amount of GPU available for buffering per host, since multiple workers can share the same pool of RAM. However, the 4GB threshold I think was just chosen as a safe lower bound. Ideally, it should be computed from the system RAM available. It should also be configurable by the user.

**Comment by chongxiaoc** [comment]
Got it, I found out user can pass in a customized `shuffle_buffer_size`.
