### ISSUE TITLE
horovod hang on with TensorBoard

### ISSUE THREAD

**Issue by burness** [horovod/horovod#297]
I run my job successfuly with no TensorBoard:

![image](https://user-images.githubusercontent.com/3112825/41097844-f58e715c-6a8b-11e8-9984-a0c97c811d85.png)
But if I uncomment the `callbacks.append(keras.callbacks.TensorBoard(config.log_dir, histogram_freq=1, batch_size = config.batch_size, write_grads=True))`

It seems to be hang on and here is the log:
![image](https://user-images.githubusercontent.com/3112825/41097880-1f471684-6a8c-11e8-8469-9e7e83408ed5.png)
why there is no rank 0 in ready ranks ?

**Comment by alsrgv** [comment]
@burness, does the training proceed after this warning or it hangs forever?

**Comment by burness** [comment]
No, It hang forever @alsrgv

**Comment by alsrgv** [comment]
@burness, very interesting.  Does that still happen if you don't set `histogram_freq=1, batch_size = config.batch_size, write_grads=True`, just write summaries?

**Comment by burness** [comment]
@alsrgv  I try, if i don't set these config, it will be successfully

**Comment by alsrgv** [comment]
@burness, what version of Horovod are you using?  I was able to get this error when I added `histogram_freq=1`:

```
Wed Jun 13 04:04:45 2018[1,0]<stderr>:ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.
```

Recent versions of Horovod will shut down in this case, but old version could get stuck.  Do you see that error before all the stall warning messages?

The way to fix this issue is to provide `validation_data` as error suggests.

**Comment by burness** [comment]
@alsrgv I use the 0.12.1 horovod, what mean is the `validation_data` ?

**Comment by alsrgv** [comment]
@burness, validation data is a parameter to `fit()` method ([docs](https://keras.io/models/sequential/#fit)).  I'm not sure `fit_generator()` works with `historgram_freq`.  Also, please update to latest Horovod - it would make diagnosing such issues easier.

**Comment by burness** [comment]
@alsrgv  Thanks! It's too fast to implement new version of Horovod, And my env is not easy to update the horovod, Could you share me what cause and I fixed this in 0.12.1

**Comment by alsrgv** [comment]
@burness, seems that you need to use `fit()` instead of `fit_generator()` to use `histogram_freq`.  This does not directly depend on Horovod version, it's just newer Horovod makes it easier to diagnose issues.

**Comment by burness** [comment]
@alsrgv  Our dataset is too large, we can't load the memory by using `fit()`

**Comment by alsrgv** [comment]
@burness, can your validation dataset fit into memory?

**Comment by richard-y** [comment]
@burness In order to log the histograms, you need to provide validation data. You can reuse your training data if you don't have validation set, just add the following arguments `fit_generator(generator=<your_data_generator>, steps_per_epoch=<your_train_steps>, validation_data=your_data_generator, validation_steps=<your_train_steps>)`. You can replace validation_steps with a smaller number if you only want to validate on a subset of your data.

**Comment by burness** [comment]
@richard-y  Thank you! Richard, Have you  try to load the large validation dataset by  using fit_generator?

**Comment by richard-y** [comment]
@burness Yes, using the same data generator for training to feed your validation dataset should work.
