### ISSUE TITLE
Pytorch lightning mnist spark example on databricks

### ISSUE THREAD

**Issue by jiwidi** [horovod/horovod#3017]
Hi!

I came across your [example](https://github.com/horovod/horovod/blob/master/examples/spark/pytorch/pytorch_lightning_spark_mnist.py) for horovod with pytorch lightning and spark (which btw has a broken link in the official [website](https://horovod.readthedocs.io/en/stable/spark_include.html) but I haven't been able to reproduce it on databricks notebooks. Is this something you have come across before? This notebooks are an interfarce were spark is accessible

**Comment by liangz1** [comment]
@jiwidi Thanks for reporting this issue. I tried it on Databricks and I got some errors saying `Dataloader returned 0 length. Please make sure that it returns at least 1 batch`. Is it the same as what you saw?
I don't have an immediate idea what is the root cause of this. Would you mind filing an engineering support ticket to Databricks so that we can allocate more time to help with this?

**Comment by jiwidi** [comment]
@liangz1 Hi sorry for late reply, yes that was indeed the problem. I will
