### ISSUE TITLE
Multi optimizers with overlapping parameters

### ISSUE THREAD

**Issue by ProHuper** [horovod/horovod#3077]
Hello, here's the problem:

I created 3 optimizers, in which opt has all parameters of the model, opt_s1 and opt_s2 only have partial parameters of the model
```python
opt = optim.Adam(net.parameters(), lr=args.lr)
opt_s1 = optim.Adam(net.stage1_params(), lr=args.lr)
opt_s2 = optim.Adam(net.stage2_params(), lr=args.lr)
```

I will use different optimizers in different epochs like this:
```python
if epoch == 1:
    opt_s1.step()
elif epoch == 2:
    opt_s2.step()
else:
    opt.step()
```

but this will trigger duplicated parameter names Errors when broadcasting the optimizers since they have overlapping parameters:

```python
opt = hvd.DistributedOptimizer(opt, named_parameters=net.named_parameters())
opt_s1 = hvd.DistributedOptimizer(opt_s1, named_parameters=net.stage1_named_params())
opt_s2 = hvd.DistributedOptimizer(opt_s2, named_parameters=net.stage2_named_params())

hvd.broadcast_parameters(opt, root_rank=0)
hvd.broadcast_parameters(opt_s1, root_rank=0)
hvd.broadcast_parameters(opt_s2, root_rank=0)
```

I solved this problem by adding prefix option when constructing named_parameters:
```python
opt = hvd.DistributedOptimizer(opt, named_parameters=net.named_parameters(prefix='all'))
opt_s1 = hvd.DistributedOptimizer(opt_s1, named_parameters=net.stage1_named_params(prefix='s1'))
opt_s2 = hvd.DistributedOptimizer(opt_s2, named_parameters=net.stage2_named_params(prefix='s2'))
```
But this caused another Error:
```
Gradients were computed more than backward_passes_per_step times before call to step().
```
Seems that horovod is monitoring those optimizers who didn't call step() after backward(), but I don't want to increase the backward_passes_per_step option. 
I tried this trick on the optimizer, which doesn't need to step() in the current iteration :

```python
opt_s2.zero_grad()
opt_s2.step()
```

Again, this caused:
```
AssertionError: optimizer.zero_grad() was called after loss.backward() but before optimizer.step() or optimizer.synchronize(). This is prohibited as it can cause a race condition.
```

Is there any method to solve this? Or overlapping optimizers is just forbidden in horovod?

**Comment by Tixxx** [comment]
Hi @ProHuper thanks for reporting the issue. It looks like your scenario can be better handled in pytorch, I see 2 options that you can try:
1. when you want to skip updating for some weights, you need to set the `requires_grad` field of that parameter to `false` so that back prop will skip the grad computation therefore horovod will not perform allreduce on its grad.
2. Instead of creating multiple optimizers, you might want to take advantage of parameter groups, keep only 1 optimizer and set learning rate for a specific parameter group to 0 when you want to skip the step() for that group, i.e.:
`optimizer = torch.optim.adam([{'params': some_params},
                             {'params': some_other_params, 'lr': 0}],  # set lr for this group to be 0 for the initial epoch, and change it 
                                                                                                   # back to desired lr in the second epoch.
                            lr=lr_for_model)`
Pytorch's [doc](https://pytorch.org/docs/stable/optim.html#per-parameter-options) has more details on this.

**Comment by ProHuper** [comment]
Thanks, @Tixxx, I see your point, seems like a good idea.
