### ISSUE TITLE
Process Sets performance issues

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#3324]
I‘m glad to see that horovod supports the Process Sets.
But there is a logic that needs to be confirmed:
In the RunLoopOnce function, a series of logic such as negotiation and wait_fore_data are executed for each process_set, so whether there is a performance problem with the execution of each process_set sequence？
<img width="899" alt="屏幕快照 2021-12-15 下午7 20 23" src="https://user-images.githubusercontent.com/41471499/146177908-2b477d43-826a-4968-90f6-6e7b50af26f9.png">

Suppose I have two Process_sets: [0,2] [1,3]
The first iteration: [0,2]Process_set will perform negotiation, wait_fore_data and other logic in turn;
The second iteration: [1,3] Process_set will perform negotiation, wait_fore_data and other logic in turn.
The logic of [1,3]Process_set will not be executed until [0,2]Process_set is executed on the host side.
In theory, such sequential execution should have an impact on performance. Especially in model parallelism, more process_set may be required, and the execution impact of this order will be greater.

Is my understanding correct? If so, can this part of the logic be optimized?

**Comment by maxhgerlach** [comment]
Hi @Richie-yan,

great to hear that you are interested in Horovod process sets!

You are right that `RunLoopOnce` iterates sequentially over the various process sets. It is important that all processes of a set are synched up correctly at all times, otherwise there would be deadlocks. For that reason the table of process sets is iterated over in a defined order. 

But please note that a process will only be really blocked here if it is part of the process set itself (there are `if (process_set.IsCurrentProcessIncluded()) {` checks around the blocks doing actual work). And if the process is part of that set, it must take part in any collective operation that's running on the set.

Therefore I do not agree that there is a performance issue in your example:
> Suppose I have two Process_sets: [0,2] [1,3]
The first iteration: [0,2]Process_set will perform negotiation, wait_fore_data and other logic in turn;
The second iteration: [1,3] Process_set will perform negotiation, wait_fore_data and other logic in turn.
The logic of [1,3]Process_set will not be executed until [0,2]Process_set is executed on the host side.

That's not true. Here, ranks 0 and 2 belong to process set [0,2], while ranks 1 and 3 belong to process set [1,3]. There is no overlap between these two process sets. So, as you said, ranks 0 and 2 will immediately start any processing for the set [0,2]. But ranks 1 and 3 will not wait for the other two ranks to finish. Rather they check (very quickly and without any negotiation) that they do not need to bother with process set [0,2] and will immediately start processing process set [1,3]. Likewise, ranks 0 and 2 will skip anything related to process set [1,3]. 

In effect, the collective operations for [0,2] and [1,3] should run concurrently because they are independent of each other.

Naturally, however, any operation on the global set [0,1,2,3] will not start until both [0,2] and [1,3] are done processing. So, for good utilization of your GPUs, the work load should be distributed as evenly as possible between the two subsets.

Does this explanation adequately address your concerns?

**Comment by Richie-yan** [comment]
Thank you for your reply.
I understand that only the current rank belongs to process_set will perform specific negotiation and communication operations, otherwise, it will enter the next iteration and will not execute specific logic until the current rank belongs to process_set.
Such processing logic will not have the performance problem.

**Comment by maxhgerlach** [comment]
> Why does each rank have to create all process_sets (is it for the convenience of users to write code?)?

This is to ensure that the order of process sets is identical everywhere and that equal process sets have the same internal ID on all ranks.

> Does the RunLoopOnce function need not traverse all process_sets? Only need to traverse the process_set that contains the process, because the process_set that does not contain the process will not perform any operations。

I guess that there is the potential for a small optimization. Currently there are a couple of checks for `process_set_id == 0` or `process_set.IsCurrentProcessIncluded()`. There could be a single check `if (!process_set.IsCurrentProcessIncluded()) { continue; }` at the top of loop to skip ahead faster.

Alternatively, each process could maintain a vector of process set IDs that actually include the running process. Then `RunLoopOnce` would not have to iterate over those entries, which it would just skip anyway.

How many different process sets do you plan to use? If it's like a couple of hundreds, I would be very surprised if these optimizations could shave off noticeable latency. Keep in mind that `RunLoopOnce` starts with a multi-millisecond sleep `<~ HOROVOD_CYCLE_TIME`.

**Comment by Richie-yan** [comment]
@maxhgerlach
Thank you for your reply.
I plan to apply Process Sets to models in parallel, such as the nlp model with hundreds of billions of parameters. In this case, a lot of process sets will be used.
I will try your optimization method . The specific delay diff will be announced here.
