### ISSUE TITLE
Keras: Support Keras reworked optimizers in Keras 2.11+

### ISSUE THREAD

**Issue by chongxiaoc** [horovod/horovod#3726]
Keras 2.11 introduces reworked optimizers as default.
See https://github.com/keras-team/keras/tree/master/keras/optimizers/optimizer_experimental

These new optimizers changed the APIs of saving and loading optimizer variables.
In PR https://github.com/horovod/horovod/pull/3725, we have to use legacy optimizers in Keras 2.11+.

Contribution is welcome to add correct load/save support for reworked optimizers in the Spark Keras estimator.

**Comment by nvcastet** [comment]
Looking more into the new keras optimizers, there is in fact nothing that prevents horovod from supporting them.
We just need to make sure we extract the good base class (which is different with the new keras optimizer) since we create dynamically our own optimizer type [here](https://github.com/horovod/horovod/blob/master/horovod/_keras/__init__.py#L51).
instead of `get_keras_optimizer_base_type(keras)` we can use `*optimizer.__class__.__bases__`.
We would also need to make sure the check [here](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/__init__.py#L1000-L1002) support all the keras optimizers.

**Comment by maxhgerlach** [comment]
implemented via #3860
