### ISSUE TITLE
Horovod: Scaling Efficiency Only 73% on 16 GPU V100

### ISSUE THREAD

**Issue by meteortwinkle** [horovod/horovod#416]
Below is a result representing the benchmark that was done on 2 servers with 8 V100 GPUs each connected by RoCE-capable 40 Gbit/s network:
fp32 mini_batch 64
1-1  Resnet101    gdr         202.78
1-4  Resnet101    gdr         650.92       162.73(650.92/4)                              80.25%
2-16 Resnet101   gdr         2379.56      148.7225(2379.56/16)                      73.34%

Our server:
GPU:V100
OS:ubuntu 16.04
CUDA:9.0
MLNX_OFED:MLNX_OFED_LINUX-4.4-1.0.0.0-ubuntu16.04-x86_64
RDMA:RoCE 
IB:X3 pro
nvidia-peer-memory:1.0.7

From the horovod's README.md , horovod achieves 90% scaling efficiency for both Inception V3 and ResNet-101. Am I missing anything？Or some guys have the same question ?

**Comment by meteortwinkle** [comment]
@alsrgv 
On our server, 4 GPUs are connected with one PCIe Switch over PCIX16.
One server have two CPU(one with 22 physical cores), one connected to the other one over QPI connection.Also,one CPU connected to the 4 GPU PCIe Switch over PCIX16.
As your said, do you think the bound was the data transmission ?
Just like my earlier question, I also doubt about the efficency of horovod's mpi message processing.
Do you have some prof tools for the mpi in horovod ?

**Comment by alsrgv** [comment]
@meteortwinkle, I think this system configuration is not great for V100s.  They really need NVLink to successfully scale within a node, and a single PCIx16 switch is very likely getting saturated.

You can use standard MPI tools for profiling MPI message processing.  [mpiP](http://mpip.sourceforge.net/) seems promising, but I have not personally tried it.

I doubt your scaling issue is due to MPI since we've tested a number of systems ourselves and always found that in case of V100, NVLink systems scaled great.

**Comment by ustcyue** [comment]
@alsrgv how about 1080Ti? Our system setup is very similar to @meteortwinkle 's. And we observed similar scaling efficiency for both 1080Ti and V100.

**Comment by alsrgv** [comment]
@ustcyue, 1080TIs would require much more modest networking, 25GbE should be sufficient.  Can you share more details about your set up and the model that you're scaling?
