### ISSUE TITLE
ASGD and SSGD

### ISSUE THREAD

**Issue by Kevinwenya** [horovod/horovod#507]
1、how can i use the ASGD in horovod, if it has this funtion.
2、when i use the SSGD in horovod, i find that the batch numbers must be equal in different process. if not, i will meet the error, like: 
[ Aborted: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message. ]

**Comment by tgaddair** [comment]
Hey @Kevinwenya, to clarify, are you referring to "asynchronous vs synchronous SGD" or "averaged vs summed SGD"?  

Based on the question details, I'm guessing the former.  Though gradients can be submitted for reduction asynchronously, we always synchronize the individual workers at each mini batch.  Due to the way the allreduce works, it wouldn't make sense to allreduce, say, only some of the ranks but not others.

It's important that the data be evenly distributed across each of the workers.  When one of the workers ends up with more data than the others, you get an error like the one you're seeing.  Can you try running the job with an equal distribution of the data?
