### ISSUE TITLE
Difference between hvd.rank() and hvd.local_rank()

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#510]
The config uses hvd.local_rank() to pin one gpu per process, to read file we use hvd.rank().
What's the difference?
When to use which?

**Comment by tgaddair** [comment]
Hey @UditGupta10, **rank** is your index within the entire ring, **local_rank** is your index within your node.

For example, you have 4 nodes and 4 GPUs each node, so you spawn 16 workers.  Every worker will have a rank [0, 15], and every worker will have a local_rank [0, 3].

You use local_rank for GPU pinning because there's typically one GPU available on the node per process.  It wouldn't make sense to use rank here because rank could be 10, but you only have 4 GPUs so there is no GPU 10.

In the MNIST example, we give each worker a separate copy of the data and give it a unique name based on the rank of the worker that will be using that data.  If all the data is being copied to local disk, then you could use local_rank here, but often we use a shared filesystem, so if you used local_rank, processes would be overwriting each other's data during the download process.

**Comment by tsauri** [comment]
I have a problem here,
I run  -np 16
But rank() is same is local_rank()
Hence when I try to pin gpu (torch.cuda.set_device(hvd.local_rank())
It local_rank gives number above [0,3], that is 0 to 16,
hence throw error
How do I fix this

**Comment by tsauri** [comment]
I have 4 machine each 4 gpu
I run mpirun -np 16 but local_rank is same as rank, and number is [0,15]
Hence I simply cannot use local_rank value for torch.set_device(hvd.local_rank())value since it become out of range.
How do I fix this

**Comment by tgaddair** [comment]
Hey @tsauri, what's your `mpirun` command?  Normally, for 4 machines with 4gpus each you'd run:

```
mpirun -np16 -H host1:4, host2:4,host3:4,host4:4 ...
```

And that would result in 4 processes per machine, with local ranks [0, 3].

**Comment by UditGupta10** [comment]
@tsauri Just confirm if you are using these lines:
# Horovod: pin GPU to be used to process local rank (one GPU per process)
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = str(hvd.local_rank())
