### ISSUE TITLE
All rank or local_rank are 0, on single node

### ISSUE THREAD

**Issue by BoseSean** [horovod/horovod#515]
Horovod always get ranks being 0.
I have tried to run the following hello world.
```
import tensorflow as tf
import horovod.tensorflow as hvd
hvd.init()
print(str(hvd.local_rank()))
```
with `mpirun`:

```
mpirun --bind-to none -x LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH) -x PATH=$(echo $PATH)\
 -x PYTHONPATH=$(echo PYTHONPATH) -x HOROVOD_MPI_THREADS_DISABLE=1  -np 8\
 -x NCCL_DEBUG=INFO $(which python) tester.py 
```
and get result
```
0
0
0
0
0
0
0
0
```
Env:
```
centos 7
cuda 9.2
tf 1.10.1
openmpi 3.1.2-cuda-gcc
# installed HOROVOD with  
HOROVOD_NCCL_HOME=/opt/nccl/2.2.13-cuda9.2 HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod    
```

**Comment by tgaddair** [comment]
Hey @BoseSean, `local_rank` and `rank` are determined by `MPI_Comm_rank`.  Usually this error is caused by having different versions of `mpicxx` and `mpirun`, as in [this](https://stackoverflow.com/questions/20287564/mpi-rank-return-same-process-number-for-all-process) StackOverflow question.

Usually this is caused by having both OpenMPI and MPICH installed, or multiple versions of OpenMPI.  Can you check that you have any other versions of MPI installed?

Also, I'd take a look at #287 and see if any of those suggestions can help.

**Comment by surak** [comment]
It is worth mentioning that hvd.local_rank will always be `0` when one compiles horovod with NCCL support but no mpi support.

**Comment by SimZhou** [comment]
I oberseved that, even if hvd.init() returns all 0, the training process is still going on correctly?
