### ISSUE TITLE
horovod doesn't overlap communication and computation in timeline?

### ISSUE THREAD

**Issue by Agoniii** [horovod/horovod#582]
I run tf_cnn_benchmarks on one node with 8GPU. 
I found horovod doesn't overlap communication and computation by checking the timeline file.
In the timeline, `unknown` means the ncclallreduce operation.
Refer to [this ](https://github.com/tensorflow/tensorflow/issues/1824#issuecomment-244251867) , `/GPU:0/stream:all compute`  indicates the computation on GPU.  

![_20181023153516](https://user-images.githubusercontent.com/18502794/47343681-40e81900-d6d9-11e8-971d-250eee94f394.png)

The ncclallreduce and backpropagation execute sequentially on GPU from the timeline. But from the source code, Horovod does overlap communication and computation. Why?
Please give me some information, thanks very much!

**Comment by Agoniii** [comment]
@alsrgv It will be great if you can look into this. Thanks!

**Comment by ustcyue** [comment]
We also observed similar pattern. We found that tensorflow can only support one computation stream, is horovod allreduce OP launching a computation kernel?
https://stackoverflow.com/questions/36098947/how-does-tensorflow-support-cuda-streams

**Comment by ustcyue** [comment]
Turns out it is a issue with tensorflow timeline, if you shut down tensorflow timeline and dump timeline using nvprof, you will find out that they are actually overlapped.

**Comment by alsrgv** [comment]
@ustcyue, great find!

**Comment by denfromufa** [comment]
@ustcyue is this issue with the tf-timeline overlap tracked anywhere in their repo?

**Comment by ustcyue** [comment]
@denfromufa seems not.  It should be a tf-timeline issue as we found the nvprof timeline matched the actual behaviour.

**Comment by denfromufa** [comment]
cc @prb12

**Comment by prb12** [comment]
The underlying NVidia CUPTI tracing library that is used by both TensorFlow and Nvidia's tools can capture a trace in various modes.  One of these modes disables concurrent kernel execution, the other doesn't.  (basically you can ask for CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL or CUPTI_ACTIVITY_KIND_KERNEL)

Several versions of the CUTPI library have had serious memory leak/corruption bugs that we discovered were triggered when using concurrent kernel tracing.  Since much of this code needs to be run in our datacenters, we can't let this be the default.

So, from time to time, concurrent tracing has been disabled in the TensorFlow tracer, and re-enabled when the bug was fixed.  I think that right now there may be an open bug with NVidia.  (but I'm not actively working on this right now)
