### ISSUE TITLE
two server with different openmpi version

### ISSUE THREAD

**Issue by Ruijin1988** [horovod/horovod#848]
I'm using ubuntu 18.04, by typing in `ompi_info`, I got 
`Package: Open MPI buildd@lcy01-amd64-009 Distribution
`
`Open MPI: 2.1.1`
But on another server, which I want to call get the version is 3.1.2.

While I'm running the `mpirun -np 16 \
    -H server1:4,server2:4` it causes an ERROR:

> Error: unknown option "--hnp-topo-sig"

May I ask, is it because the two servers have different openmpi version?

Thanks!

**Comment by alsrgv** [comment]
@Ruijin1988, maybe.  You must use the same Open MPI version everywhere.

**Comment by AnkBurov** [comment]
@Ruijin1988 I've just been struggling with this for some time. AFAIK no, unfortunately openmpi doesn't have a backward compatibility like at all. Even if the other side of the MPI communication will have same flags compatibility, in the end openmpi will raise an error that versions of the local side and remote side are different. 
So you will have to have the exact same version everywhere :disappointed:

**Comment by Ruijin1988** [comment]
Thanks @alsrgv  @AnkBurov . You're right that the versions should be consistent.  Now I'm facing another issue, while I was trying to use another server, it gives me an error like:
`python3: can't open file 'keras_imagenet_resnet50.py': [Errno 2] No such file or directory`.
But it works totally fine with localhost. Do you have any idea what's going wrong here?

Thanks!

**Comment by AnkBurov** [comment]
Do you have the keras_imagenet_resnet50.py file on the server?

**Comment by Ruijin1988** [comment]
@AnkBurov Thanks for your timely response. I have the 'keras_imagenet_resnet50.py' on my localhost. Does that mean the server should also have the same code? If so, where should I put the code and specify the running directory? Thanks!

**Comment by AnkBurov** [comment]
Yes, you need to have the exact same Python script on all servers where you're planning to run distributed training. This also means that all these scripts on each worker should have an access to your features dataset in the same manner. So when you're runnung `mpirun ... server1,server2 python3 script.py` your MPI implementation will execute this script (these scripts *) on all specified servers simultaneously, but due to Horovod DistributedOptimizer these servers will somehow communicate with each other and decide which part of the dataset each worker will train on. AFAIK Horovod does nothing with Python executions and dataset moving - it only coordinates the training between specified servers. For more details check this issue, it helped me a lot - https://github.com/horovod/horovod/issues/820

> `python3: can't open file 'PATH/TO/keras_imagenet_resnet50.py': [Errno 2] No such file or directory`

I don't know which MPI implementation you're using, but with MPICH I managed to succeed only when I used absolute paths from the linux root `/` and the `-wdir /` flag. Try to move keras_imagenet_resnet50.py to something like `/some/keras_imagenet_resnet50.py` and execute in mpirun accordingly.

The best approach I worked out so far is to create a network storage, mount it on all distributed training servers under the same mapping like `/features-store`, upload there a dataset, a Python script and Python virtual environment for this script. Therefore all servers under the same virtual environment execute the same Python script and train on the same dataset. 
Maybe it's not the best approach, but it worked for me and eased up a little the pain with the python scripts, datasets and different paths everywhere.

**Comment by AnkBurov** [comment]
Same script - I mean they can be physically different scripts with the same code, but it's pain to edit them, so one script in a network storage works better.

**Comment by Ruijin1988** [comment]
Hi @AnkBurov , I think you're right. I put the code on a shared disk and it's working, but conditionally. I'm able to use only the server, or the localhost. But if i'm trying to call them together like:
`mpirun -np 2 -H localhost:1, deeplearning:1 ........` 
and then ends up with following error:
`[deeplearning:32578] [[64792,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355`
`An internal error has occurred in ORTE:
[[64792,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)
This is something that should be reported to the developers.
`
Do you happen to have the same issue?  Great appreciate your help!

**Comment by AnkBurov** [comment]
@Ruijin1988 can't help you with it - I see you're using openmpi. Personally I tried openmpi and had little success with it - in the end I managed to get it working between servers, but when I tried to run mpirun on a different server from my computer I got an error which was reported in an issue tracker as a bug of openmpi in Ubuntu. In your case I would suggest enabling verbose logging of openmpi and try to figure out what is happening. I tried to update openmpi and discovered that newer version of openmpi doesn't support `@` symbol in hostnames. I won't say that openmpi is a bad software, but... :smile: 

In my case I'm using MPICH implementation of MPI standard and it worked fine for me - like this: `/usr/lib64/mpich-3.2/bin/mpirun -hosts username@server1,username@server2 -wdir / -genvnone -localhost 10.199.40.181 hostname`
