### ISSUE TITLE
mpirun noticed that process rank 0 with PID 0 

### ISSUE THREAD

**Issue by GwinSalbor** [horovod/horovod#926]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch)
2. Framework version: tensorflow-gpu==1.4.0, keras==2.0.8, torch==1.0.1
3. Horovod version:0.15.2
4. MPI version:4.0.0
5. CUDA and cudann version: 8.0, 6.0
6. NCCL version:2.2.13
7. Python version: 3.5.2
8. OS and version: Ubuntu 16.04 lts
9. Processor: Intel® Celeron(R) CPU G3930

**Issue**
mpirun noticed that process rank 0 with PID 0 on node exited on signal 4 (Illegal instruction).
![image](https://user-images.githubusercontent.com/28218333/54549934-2aaa6480-49bc-11e9-973e-7305cab4f649.png)

**Comment by alsrgv** [comment]
@GwinSalbor, I suspect that the issue is with some piece of software pre-compiled with AVX instructions, while your processor [does not support](https://ark.intel.com/content/www/us/en/ark/products/97452/intel-celeron-processor-g3930-2m-cache-2-90-ghz.html) them.

Does simply running `python -c "import tensorflow"` succeed?

If it does, can you try to follow [this guide](https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu/40223712) to determine which instruction causes the failure and which library contains it (by querying `bt` in `gdb`)?

**Comment by GwinSalbor** [comment]
Thanks, problem was fixed by downgrading horovod version to 0.14.1.
