### ISSUE TITLE
Could not resolve hostname localhost:4: Name or service not known

### ISSUE THREAD

**Issue by LeavesLei** [horovod/horovod#951]
when I execute:  **horovodrun -np 4 -H localhost:4 python train.py**
there is a error:

```
jiangyy@amax:~/leishiye_horovod$ horovodrun -np 4 -H localhost:4 python train.py
ssh: Could not resolve hostname localhost:4: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```

**Comment by alsrgv** [comment]
@LeavesLei, please upgrade your Open MPI to 4.0.0.  You can use [this command](https://github.com/horovod/horovod/blob/master/Dockerfile#L40).

**Comment by LeavesLei** [comment]
@alsrgv , There has already been OpenMPI with a old version. I don't know how to upgrate it. Or I must install a new OpenMPI 4.0.0?

**Comment by alsrgv** [comment]
Please uninstall older OpenMPI using a package manager and just install a new OpenMPI 4.0.0.

Thanks,
Alex
________________________________

**Comment by LeavesLei** [comment]
Thanks^_^

**Comment by haif-liu** [comment]
I also meet this problem and the version of openmpi is 4.0.0.

horovodrun -np 1 -H localhost:1 python test.py

ssh: Could not resolve hostname localhost:1: Temporary failure in name resolution
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

**Comment by alsrgv** [comment]
@haif-liu, let's follow up in #1032

**Comment by 652994331** [comment]
@alsrgv  Hi, can i ask a quick question? I was using horovod multi-gpu in my server, it ok. Recently i moved to a new server and already got every thing for the environment, but when i used same command as my old server, it said:
![image](https://user-images.githubusercontent.com/51428350/64043248-bb16d480-cb18-11e9-995a-527312a08929.png)
i guess ther's something wrong with "localhost". could you please help me out, thanks!

**Comment by abditag2** [comment]
@652994331 can you add --verbose flag and post the output?

**Comment by abditag2** [comment]
answered in https://github.com/horovod/horovod/issues/1371#event-2598637245
